### ISSUE TITLE
SIGSEGV: Illegal storage access

### ISSUE THREAD

**Issue by gnois** [def-/nim-iterutils#3]
```
> nim c iterutils.nim
Hint: system [Processing]
Hint: iterutils [Processing]
....
Hint: parseutils [Processing]
SIGSEGV: Illegal storage access. (Try to compile with -d:useSysAssert -d:useGcAssert for details.)
```

Got here from your informative blog http://hookrace.net/blog/nim-adventures/
Tried to compile but can't. Compiler is v0.10.2.

**Comment by def-** [comment]
Thanks, hadn't tested this with nim 0.10.2 yet, reported 2 bugs in the compiler:
https://github.com/Araq/Nim/issues/1834
https://github.com/Araq/Nim/issues/1836

**Comment by def-** [comment]
Module finally works again, only this bug seems to remain: https://github.com/nim-lang/Nim/issues/3837
