### ISSUE TITLE
example in https://hookrace.net/nim-iterutils/iterutils.html broken

### ISSUE THREAD

**Issue by timotheecour** [def-/nim-iterutils#4]
```nim
#test.nim

import iterutils
from sequtils import toSeq
import sugar

proc test1()=
  for i in filter(map(filter(2..10, proc(x: int): bool = x mod 2 == 0),
           proc(x: int): int = x * 2), proc(x: int): bool = x mod 8 == 0):
    echo i

  var s = toSeq (2..10).filter(proc(x): bool = x mod 2 == 0).
      map(proc(x): int = x * 2).filter(proc(x): bool = x mod 8 == 0)
  echo s

  var a = (2..10).filter(proc(x: int): bool = x mod 2 == 0)
  var b = a.map((x: int) => x * 2)
  for i in b.map((x: int) => x + 2):
    echo i
test1()
```

gives:
test.nim(19, 17) Error: invalid indentation

fixing that gives other errors, and nothing prints

This example should be a test file in this repo so others can fix it (ideally something ran by `nimble test iterutils`)

## links
* https://hookrace.net/nim-iterutils/iterutils.html

**Comment by def-** [comment]
I think at some point iterutils was broken by the compiler. Haven't checked if it even works again. I think there are better libs for this kind of stuff nowadays anyway.

**Comment by timotheecour** [comment]
could that be related to https://github.com/nim-lang/Nim/issues/8188 (that I just filed) ? do you remember with which version of the compiled did it work? I'm specifically referring to iterator composition case (not the other errors).
Basically I'm wondering whether https://github.com/nim-lang/Nim/issues/8188 is a regression.

> I think there are better libs for this kind of stuff nowadays anyway

Such as?
If so, the readme.md should point to those and also show limitations of this library to save people time. That being said, the code is clean and simpler that ones I could find in alternative libraries IIRC; and should just work ; I hope it's a fixable compiler bug.

**Comment by def-** [comment]
Something like this:
https://github.com/alehander42/zero-functional
But I haven't tried it yet. If you do and find it satisfactory, update me and I'll add a note to the readme.

**Comment by timotheecour** [comment]
I have tried it; IIRC this didn't work with arbitrary iterators, see full thread here: https://github.com/alehander42/zero-functional/issues/20 (even though it was closed, IIRC you wouldn't be able to use that with iterators who don't have a known length, making a ton of use cases impossible).

I also just added your repo to https://github.com/alehander42/zero-functional/issues/21

**Comment by timotheecour** [comment]
> But I haven't tried it yet. If you do and find it satisfactory, update me and I'll add a note to the readme.

just sent https://github.com/def-/nim-iterutils/pull/5

**Comment by timotheecour** [comment]
@def- I just verified that  https://github.com/nim-lang/Nim/issues/8188 is indeed a regression, and that your repo did work with iterator composition with nimrod 0.9.4 ( I tried 0.9.4 after looking at your commit logs and past issues, eg https://github.com/def-/nim-iterutils/issues/2#issuecomment-53605327)

so your code in 40b83d2de580b93c5ef96100a72df1ea4981a7a8 worked with 0.9.4
